arch: "PoundNet"
resume: null
name: "globalsigreg_poundnet_ViTL_Progan"

train:
  pipeline: engine.ledet_trainer_sigreg
  seed: 38534
  train_epochs: 1
  gradient_accumulation_steps: 1
  check_val_every_n_epoch: 1

  lambda_reg: 1e-2
  sigreg_knots: 17
  sigreg_t_max: 3.0
  sigreg_num_slices: 256

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: True
    lr: 1e-4
    weight_decay: 1e-3
    betas: [ 0.9, 0.999 ]

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: ${train.train_epochs}

model:
  NAME: "ViT-L/14"
  N_CTX_VISION: 16
  N_CTX_TEXT: 16
  CTX_INIT: False
  PROMPT_DEPTH_VISION: 8
  PROMPT_DEPTH_TEXT: 8
  PROMPT_NUM_TEXT: 1

datasets:
  base_path: "/home/data/yabin/DF-arrow"
  train:
    source:
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/ForenSynths',
          sub_sets: ["airplane", "bird", "bottle", "car", "chair", "diningtable", "horse", "person", "sheep", "train",
                       "bicycle", "boat", "bus", "cat", "cow", "dog", "motorbike", "pottedplant", "sofa", "tvmonitor"],
          split: 'train_binary' }
    multicalss_names: ["airplane", "bird", "bottle", "car", "chair", "diningtable", "horse", "person", "sheep", "train",
                       "bicycle", "boat", "bus", "cat", "cow", "dog", "motorbike", "pottedplant", "sofa", "tvmonitor"]
    batch_size: 32
    loader_workers: 16
    trsf:
      - _target_: torchvision.transforms.Resize
        size: 256
      - _target_: torchvision.transforms.RandomResizedCrop
        size: 224
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: data.DataAugment
        blur_prob: 0.1
        blur_sig: [ 0.0, 3.0 ]
        jpg_prob: 0.1
        jpg_method: [ 'cv2', 'pil' ]
        jpg_qual: [ 60, 100 ]
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.48145466, 0.4578275, 0.40821073 ]
        std: [ 0.26862954, 0.26130258, 0.27577711 ]

  val:
    source:

      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/DIF',
          sub_sets: [ 'dalle_2',  'dalle_mini',  'glide',  'mj',  'sd14',  'sd21', ],
          split: 'test',
          benchmark_name: 'DIF'}

    batch_size: 128
    loader_workers: 32
    trsf:
      - _target_: data.RandomCompress
        method: "JPEG"
        qf: [70, 100]
      - _target_: torchvision.transforms.Resize
        size: 256
      - _target_: torchvision.transforms.CenterCrop
        size: 224
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.48145466, 0.4578275, 0.40821073]
        std: [0.26862954, 0.26130258, 0.27577711]

  test:
    source:
      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/ForenSynths',
          sub_sets: [ "biggan", "crn", "cyclegan", "deepfake", "gaugan", "imle", "progan", "san", "seeingdark", "stargan",
                    "stylegan", "stylegan2", "whichfaceisreal"  ],
          split: 'test',
          benchmark_name: 'ForenSynths'}

      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/GANGen-Detection',
          sub_sets: [ "AttGAN", "BEGAN", "CramerGAN", "GANimation", "InfoMaxGAN", "MMDGAN", "RelGAN", "S3GAN", "SNGAN", "STGAN" ],
          split: 'test',
          benchmark_name: 'GANGen-Detection' }

      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/DIF',
          sub_sets: [ 'dalle_2',  'dalle_mini',  'glide',  'mj',  'sd14',  'sd21', ],
          split: 'test',
          benchmark_name: 'DIF' }

      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/DiffusionForensics',
          sub_sets: [ 'imagenet_sdv1', 'imagenet_adm', 'lsun_bedroom_sdv1_new1', 'lsun_bedroom_sdv1_new2',
                    'lsun_bedroom_adm', 'lsun_bedroom_iddpm', 'lsun_bedroom_ddpm', 'lsun_bedroom_pndm',
                    'lsun_bedroom_sdv2', 'lsun_bedroom_ldm', 'lsun_bedroom_vqdiffusion', 'lsun_bedroom_if',
                    'lsun_bedroom_dalle2', 'lsun_bedroom_midjourney', 'celebahq_sdv2', 'celebahq_if',
                    'celebahq_dalle2', 'celebahq_midjourney' ],
          split: 'test',
          benchmark_name: 'DiffusionForensics' }

      - { target: data.ArrowDatasets,
          data_root: '${datasets.base_path}/Ojha',
          sub_sets: [ "dalle", "glide_100_10", "glide_100_27", "glide_50_27", "guided", "ldm_100", "ldm_200", "ldm_200_cfg" ],
          split: 'test',
          benchmark_name: 'Ojha' }

    batch_size: 64
    loader_workers: 16
    trsf:
      - _target_: data.RandomCompress
        method: "JPEG"
        qf: [ 90, 90 ]
      - _target_: torchvision.transforms.Resize
        size: 256
      - _target_: torchvision.transforms.CenterCrop
        size: 224
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [ 0.48145466, 0.4578275, 0.40821073 ]
        std: [ 0.26862954, 0.26130258, 0.27577711 ]


